export const BOTAO_CLICADO_SUCESS = 'BOTAO_CLICADO_SUCESS';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';

export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_UPDATED_SUCESS = 'REGISTER_UPDATED_SUCESS';
export const REGISTER_CREATED_SUCESS = 'REGISTER_CREATED_SUCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
